// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NFCWebBlazor.Models;

public partial class NFCNVLContext : DbContext
{
    public NFCNVLContext(DbContextOptions<NFCNVLContext> options)
        : base(options)
    {
    }

    public virtual DbSet<NvlBarcodeHangHoa> NvlBarcodeHangHoas { get; set; }

    public virtual DbSet<NvlChiTietKhuVuc> NvlChiTietKhuVucs { get; set; }

    public virtual DbSet<NvlChiTietKhuVucLog> NvlChiTietKhuVucLogs { get; set; }

    public virtual DbSet<NvlDonDatHang> NvlDonDatHangs { get; set; }

    public virtual DbSet<NvlDonDatHangChiPhiKhac> NvlDonDatHangChiPhiKhacs { get; set; }

    public virtual DbSet<NvlDonDatHangFileAttach> NvlDonDatHangFileAttaches { get; set; }

    public virtual DbSet<NvlDonDatHangItem> NvlDonDatHangItems { get; set; }

    public virtual DbSet<NvlDuyetGiaItem> NvlDuyetGiaItems { get; set; }

    public virtual DbSet<NvlDuyetGium> NvlDuyetGia { get; set; }

    public virtual DbSet<NvlGhiNoHieuChinh> NvlGhiNoHieuChinhs { get; set; }

    public virtual DbSet<NvlHangHoa> NvlHangHoas { get; set; }

    public virtual DbSet<NvlHangHoaDungChungGroup> NvlHangHoaDungChungGroups { get; set; }

    public virtual DbSet<NvlHangHoaDungChungItem> NvlHangHoaDungChungItems { get; set; }

    public virtual DbSet<NvlHangHoaDvtquyDoi> NvlHangHoaDvtquyDois { get; set; }

    public virtual DbSet<NvlHangHoaHanSuDung> NvlHangHoaHanSuDungs { get; set; }

    public virtual DbSet<NvlHangHoaMaNhanDien> NvlHangHoaMaNhanDiens { get; set; }

    public virtual DbSet<NvlInPhieu> NvlInPhieus { get; set; }

    public virtual DbSet<NvlInPhieuTempM> NvlInPhieuTempMs { get; set; }

    public virtual DbSet<NvlKeHoachChiTiet> NvlKeHoachChiTiets { get; set; }

    public virtual DbSet<NvlKeHoachGhiChu> NvlKeHoachGhiChus { get; set; }

    public virtual DbSet<NvlKeHoachMuaHangItem> NvlKeHoachMuaHangItems { get; set; }

    public virtual DbSet<NvlKeHoachMuaHangItemLog> NvlKeHoachMuaHangItemLogs { get; set; }

    public virtual DbSet<NvlKeHoachSp> NvlKeHoachSps { get; set; }

    public virtual DbSet<NvlKehoachMuaHang> NvlKehoachMuaHangs { get; set; }

    public virtual DbSet<NvlKhachHang> NvlKhachHangs { get; set; }

    public virtual DbSet<NvlKhuVuc> NvlKhuVucs { get; set; }

    public virtual DbSet<NvlKyDuyet> NvlKyDuyets { get; set; }

    public virtual DbSet<NvlKyDuyetHanMuc> NvlKyDuyetHanMucs { get; set; }

    public virtual DbSet<NvlKyDuyetItem> NvlKyDuyetItems { get; set; }

    public virtual DbSet<NvlLienKetDhmua> NvlLienKetDhmuas { get; set; }

    public virtual DbSet<NvlMaKho> NvlMaKhos { get; set; }

    public virtual DbSet<NvlMaMau> NvlMaMaus { get; set; }

    public virtual DbSet<NvlMsgManage> NvlMsgManages { get; set; }

    public virtual DbSet<NvlNghiemThuBienBan> NvlNghiemThuBienBans { get; set; }

    public virtual DbSet<NvlNghiemThuBienBanItem> NvlNghiemThuBienBanItems { get; set; }

    public virtual DbSet<NvlNghiemThuDienGiai> NvlNghiemThuDienGiais { get; set; }

    public virtual DbSet<NvlNghiemThuHangMucDienGiai> NvlNghiemThuHangMucDienGiais { get; set; }

    public virtual DbSet<NvlNghiemThuItem> NvlNghiemThuItems { get; set; }

    public virtual DbSet<NvlNghiemThuMaster> NvlNghiemThuMasters { get; set; }

    public virtual DbSet<NvlNghiemThuSettingColumn> NvlNghiemThuSettingColumns { get; set; }

    public virtual DbSet<NvlNghiemThuTieuChuan> NvlNghiemThuTieuChuans { get; set; }

    public virtual DbSet<NvlNhaCungCap> NvlNhaCungCaps { get; set; }

    public virtual DbSet<NvlNhaCungCapHd> NvlNhaCungCapHds { get; set; }

    public virtual DbSet<NvlNhapXuat> NvlNhapXuats { get; set; }

    public virtual DbSet<NvlNhapXuatItem> NvlNhapXuatItems { get; set; }

    public virtual DbSet<NvlNhapXuatItemLog> NvlNhapXuatItemLogs { get; set; }

    public virtual DbSet<NvlNhapXuatLyDo> NvlNhapXuatLyDos { get; set; }

    public virtual DbSet<NvlNhomHang> NvlNhomHangs { get; set; }

    public virtual DbSet<NvlNoiBo> NvlNoiBos { get; set; }

    public virtual DbSet<NvlReportDetail> NvlReportDetails { get; set; }

    public virtual DbSet<NvlSoDoKho> NvlSoDoKhos { get; set; }

    public virtual DbSet<NvlThanhToan> NvlThanhToans { get; set; }

    public virtual DbSet<NvlThanhToanItem> NvlThanhToanItems { get; set; }

    public virtual DbSet<NvlViTri> NvlViTris { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<NvlBarcodeHangHoa>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlBarcodeHangHoa");

            entity.Property(e => e.Barcode).HasMaxLength(100);
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlChiTietKhuVuc>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlChiTietKhuVuc");

            entity.HasIndex(e => new { e.MaHang, e.ArticleNumber, e.KhuVuc, e.MaSp }, "Unique_NvlChiTietKhuVuc").IsUnique();

            entity.HasIndex(e => new { e.MaSp, e.ArticleNumber, e.MaHang, e.KhuVuc }, "sqlchitietduplicate").IsUnique();

            entity.Property(e => e.ArticleNumber).HasMaxLength(100);
            entity.Property(e => e.ChatLuong).HasMaxLength(100);
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.KhuVuc)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.MaHang)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaSp)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("MaSP");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SlquyDoi).HasColumnName("SLQuyDoi");
            entity.Property(e => e.UserInsert).HasMaxLength(100);

            entity.HasOne(d => d.MaHangNavigation).WithMany(p => p.NvlChiTietKhuVucs)
                .HasForeignKey(d => d.MaHang)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NvlChiTietKhuVuc_NvlHangHoa");
        });

        modelBuilder.Entity<NvlChiTietKhuVucLog>(entity =>
        {
            entity.HasKey(e => e.SerialLog);

            entity.ToTable("NvlChiTietKhuVuc_Log");

            entity.Property(e => e.SerialLog).HasColumnName("Serial_Log");
            entity.Property(e => e.ArticleNumber).HasMaxLength(100);
            entity.Property(e => e.ChatLuong).HasMaxLength(100);
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.KhuVuc)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.MaHang)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaSp)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("MaSP");
            entity.Property(e => e.NgayInsert).HasColumnType("datetime");
            entity.Property(e => e.NgayUpdate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SlquyDoi).HasColumnName("SLQuyDoi");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.UserUpdate).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlDonDatHang>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlDonDatHang");

            entity.Property(e => e.Active).HasDefaultValue(1);
            entity.Property(e => e.Dvtt)
                .HasMaxLength(100)
                .HasColumnName("DVTT");
            entity.Property(e => e.GhiChu).HasMaxLength(1000);
            entity.Property(e => e.KhuVuc).HasMaxLength(100);
            entity.Property(e => e.LoaiDonHang).HasMaxLength(100);
            entity.Property(e => e.MaDatHang).HasMaxLength(100);
            entity.Property(e => e.MaNcc)
                .HasMaxLength(100)
                .HasColumnName("MaNCC");
            entity.Property(e => e.NgayDatHang).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgayMax).HasColumnType("date");
            entity.Property(e => e.NgayTao).HasColumnType("date");
            entity.Property(e => e.NoiDungDeNghi).HasMaxLength(1500);
            entity.Property(e => e.PhongBan).HasMaxLength(100);
            entity.Property(e => e.SoHd)
                .HasMaxLength(100)
                .HasColumnName("SoHD");
            entity.Property(e => e.Sttdh).HasColumnName("STTDH");
            entity.Property(e => e.Sttdhncc).HasColumnName("STTDHNCC");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlDonDatHangChiPhiKhac>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlDonDatHang_ChiPhiKhac");

            entity.Property(e => e.Dvt)
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NoiDung)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.UserInsert).HasMaxLength(100);

            entity.HasOne(d => d.SerialDatHangNavigation).WithMany(p => p.NvlDonDatHangChiPhiKhacs)
                .HasForeignKey(d => d.SerialDatHang)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_NvlDonDatHang_ChiPhiKhac_NvlDonDatHang");
        });

        modelBuilder.Entity<NvlDonDatHangFileAttach>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlDonDatHang_FileAttach");

            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgayUpload).HasColumnType("datetime");
            entity.Property(e => e.NoiDung).HasMaxLength(200);
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.UserUpload).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlDonDatHangItem>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlDonDatHangItem");

            entity.Property(e => e.DienGiai).HasMaxLength(500);
            entity.Property(e => e.DonGia).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.DuyetItemMsg).HasMaxLength(500);
            entity.Property(e => e.Dvt)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.GiaTri).HasDefaultValue(1);
            entity.Property(e => e.KeyGroup).HasMaxLength(50);
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.MaNcc)
                .HasMaxLength(100)
                .HasColumnName("MaNCC");
            entity.Property(e => e.NgayDknhapKho)
                .HasColumnType("date")
                .HasColumnName("NgayDKNhapKho");
            entity.Property(e => e.NgayEdit)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SerialMaDh).HasColumnName("SerialMaDH");
            entity.Property(e => e.SldatHang)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("SLDatHang");
            entity.Property(e => e.Slhuy)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("SLHuy");
            entity.Property(e => e.SltheoDoi)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("SLTheoDoi");
            entity.Property(e => e.Stt).HasColumnName("STT");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);

            entity.HasOne(d => d.MaNccNavigation).WithMany(p => p.NvlDonDatHangItems)
                .HasForeignKey(d => d.MaNcc)
                .HasConstraintName("FK_NvlDonDatHangItem_NvlNhaCungCap");

            entity.HasOne(d => d.SerialMaDhNavigation).WithMany(p => p.NvlDonDatHangItems)
                .HasForeignKey(d => d.SerialMaDh)
                .HasConstraintName("FK_NvlDonDatHangItem_NvlDonDatHang");
        });

        modelBuilder.Entity<NvlDuyetGiaItem>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlDuyetGiaItem");

            entity.HasIndex(e => new { e.SerialLink, e.KeyGroup }, "SerialLink_KeyGroup");

            entity.HasIndex(e => e.KeyGroup, "UQ_NvlDuyetGiaItem").IsUnique();

            entity.Property(e => e.DinhMuc).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.DonGiaDuyet).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.DonGiaTheoDvt)
                .HasColumnType("decimal(18, 4)")
                .HasColumnName("DonGiaTheoDVT");
            entity.Property(e => e.Dvt)
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.GhiChu).HasMaxLength(150);
            entity.Property(e => e.GiaDangMua).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.KeyGroup).HasMaxLength(30);
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.MaNccduyet)
                .HasMaxLength(100)
                .HasColumnName("MaNCCDuyet");
            entity.Property(e => e.MsgKhongDuyet).HasMaxLength(500);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NhaCungCapDuyet).HasMaxLength(150);
            entity.Property(e => e.SlduToan)
                .HasColumnType("decimal(18, 4)")
                .HasColumnName("SLDuToan");
            entity.Property(e => e.Stt).HasColumnName("STT");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.TinhTrangDuyet).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.XuatXu).HasMaxLength(150);
        });

        modelBuilder.Entity<NvlDuyetGium>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.Property(e => e.ChonNhaCungCap).HasMaxLength(200);
            entity.Property(e => e.CuocVanChuyen).HasMaxLength(150);
            entity.Property(e => e.DuAnHanMuc).HasMaxLength(150);
            entity.Property(e => e.Dvt)
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.KetQua).HasMaxLength(100);
            entity.Property(e => e.LoaiDuyetGia).HasMaxLength(100);
            entity.Property(e => e.LyDo).HasMaxLength(100);
            entity.Property(e => e.MaDn)
                .HasMaxLength(100)
                .HasColumnName("MaDN");
            entity.Property(e => e.Ngay).HasColumnType("date");
            entity.Property(e => e.NgayApDung).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgayKetThuc).HasColumnType("date");
            entity.Property(e => e.NguoiDn)
                .HasMaxLength(100)
                .HasColumnName("NguoiDN");
            entity.Property(e => e.NhaMay).HasMaxLength(100);
            entity.Property(e => e.PhongBan).HasMaxLength(100);
            entity.Property(e => e.Stt).HasColumnName("STT");
            entity.Property(e => e.ThueGtgt)
                .HasMaxLength(150)
                .HasColumnName("ThueGTGT");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlGhiNoHieuChinh>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlGhiNoHieuChinh");

            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.LyDo).HasMaxLength(100);
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.MaKho).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NhaMay).HasMaxLength(100);
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlHangHoa>(entity =>
        {
            entity.HasKey(e => e.MaHang).HasName("PK_HangHoa");

            entity.ToTable("NvlHangHoa");

            entity.HasIndex(e => e.MaHang, "UQ__NvlHangH__19C0DB1C3B63AAA0").IsUnique();

            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.ChatLuong).HasMaxLength(100);
            entity.Property(e => e.Dvt)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.Flag).HasColumnName("flag");
            entity.Property(e => e.GhiChu).HasMaxLength(100);
            entity.Property(e => e.KeySearch).HasMaxLength(1000);
            entity.Property(e => e.MaKhac).HasMaxLength(100);
            entity.Property(e => e.MaMau).HasMaxLength(100);
            entity.Property(e => e.MaNhom)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaPdoc)
                .HasMaxLength(50)
                .HasColumnName("MaPDOC");
            entity.Property(e => e.MaSpgroup)
                .HasMaxLength(100)
                .HasColumnName("MaSPGroup");
            entity.Property(e => e.MaxTk).HasColumnName("MaxTK");
            entity.Property(e => e.MinTk).HasColumnName("MinTK");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PathImg).HasMaxLength(1000);
            entity.Property(e => e.PhanLoaiDm)
                .HasMaxLength(100)
                .HasColumnName("PhanLoaiDM");
            entity.Property(e => e.QuyCach).HasMaxLength(100);
            entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            entity.Property(e => e.Slcont).HasColumnName("SLCont");
            entity.Property(e => e.TenHang)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TenSppdoc)
                .HasMaxLength(200)
                .HasColumnName("TenSPPDoc");
            entity.Property(e => e.TrangThai).HasMaxLength(50);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.XuatXu).HasMaxLength(100);

            entity.HasOne(d => d.MaNhomNavigation).WithMany(p => p.NvlHangHoas)
                .HasForeignKey(d => d.MaNhom)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NvlHangHoa_NvlNhomHang");
        });

        modelBuilder.Entity<NvlHangHoaDungChungGroup>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlHangHoaDungChungGroup");

            entity.Property(e => e.GroupName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.KhuVuc).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlHangHoaDungChungItem>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlHangHoaDungChungItem");

            entity.Property(e => e.MaHang)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SlquyDoi).HasColumnName("SLQuyDoi");
            entity.Property(e => e.UserInsert).HasMaxLength(100);

            entity.HasOne(d => d.SerialGroupNavigation).WithMany(p => p.NvlHangHoaDungChungItems)
                .HasForeignKey(d => d.SerialGroup)
                .HasConstraintName("FK_NvlHangHoaDungChungItem_NvlHangHoaDungChungGroup");
        });

        modelBuilder.Entity<NvlHangHoaDvtquyDoi>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlHangHoa_DVTQuyDoi");

            entity.Property(e => e.Dvt1)
                .HasMaxLength(100)
                .HasColumnName("DVT1");
            entity.Property(e => e.Dvt2)
                .HasMaxLength(100)
                .HasColumnName("DVT2");
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlHangHoaHanSuDung>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlHangHoa_HanSuDung");

            entity.Property(e => e.Dvt)
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.GhiChu).HasMaxLength(100);
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlHangHoaMaNhanDien>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlHangHoa_MaNhanDien");

            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.MaNhanDien).HasMaxLength(200);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlInPhieu>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlInPhieu");

            entity.Property(e => e.ArticleNumber).HasMaxLength(50);
            entity.Property(e => e.Barcode).HasMaxLength(100);
            entity.Property(e => e.ChatLuong).HasMaxLength(100);
            entity.Property(e => e.DauTuan).HasMaxLength(100);
            entity.Property(e => e.Dvt)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.KhachHangXuatXu)
                .HasMaxLength(100)
                .HasColumnName("KhachHang_XuatXu");
            entity.Property(e => e.KhuVuc).HasMaxLength(100);
            entity.Property(e => e.MaCt).HasColumnName("MaCT");
            entity.Property(e => e.MaGn)
                .HasMaxLength(100)
                .HasColumnName("MaGN");
            entity.Property(e => e.MaHang)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaKien).HasMaxLength(100);
            entity.Property(e => e.MaSp)
                .HasMaxLength(50)
                .HasColumnName("MaSP");
            entity.Property(e => e.NgayHetHan).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgaySanXuat).HasColumnType("date");
            entity.Property(e => e.SerialCt).HasColumnName("SerialCT");
            entity.Property(e => e.SoLo).HasMaxLength(100);
            entity.Property(e => e.SoXe).HasMaxLength(20);
            entity.Property(e => e.UserInsert).HasMaxLength(100);

            entity.HasOne(d => d.MaHangNavigation).WithMany(p => p.NvlInPhieus)
                .HasForeignKey(d => d.MaHang)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NvlInPhieu_NvlHangHoa");
        });

        modelBuilder.Entity<NvlInPhieuTempM>(entity =>
        {
            entity.HasKey(e => e.Serial).HasName("PK_INMS");

            entity.Property(e => e.DienGiai).HasMaxLength(200);
            entity.Property(e => e.Flag).HasColumnName("flag");
            entity.Property(e => e.GhiChu).HasMaxLength(250);
            entity.Property(e => e.LyDo).HasMaxLength(100);
            entity.Property(e => e.MaCt)
                .HasMaxLength(50)
                .HasColumnName("MaCT");
            entity.Property(e => e.MaDn)
                .HasMaxLength(100)
                .HasColumnName("MaDN");
            entity.Property(e => e.MaGn)
                .HasMaxLength(100)
                .HasColumnName("MaGN");
            entity.Property(e => e.MaKho).HasMaxLength(100);
            entity.Property(e => e.Ngay).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NghiemThu).HasMaxLength(100);
            entity.Property(e => e.NguoiDn)
                .HasMaxLength(100)
                .HasColumnName("NguoiDN");
            entity.Property(e => e.NhaMay).HasMaxLength(100);
            entity.Property(e => e.Ponumber)
                .HasMaxLength(100)
                .HasColumnName("PONumber");
            entity.Property(e => e.Sttct).HasColumnName("STTCT");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlKeHoachChiTiet>(entity =>
        {
            entity.ToTable("NvlKeHoachChiTiet");

            entity.Property(e => e.Id)
                .HasMaxLength(100)
                .HasColumnName("ID");
            entity.Property(e => e.ArticleNumber).HasMaxLength(100);
            entity.Property(e => e.DinhMucHaoHut).HasDefaultValue(0.10000000000000001);
            entity.Property(e => e.IdKeHoach)
                .HasMaxLength(100)
                .HasColumnName("ID_KeHoach");
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.Ngay).HasColumnType("datetime");
            entity.Property(e => e.NhaMay).HasMaxLength(100);
            entity.Property(e => e.Slkh).HasColumnName("SLKH");
            entity.Property(e => e.SltheoDoi).HasColumnName("SLTheoDoi");
            entity.Property(e => e.Stt)
                .ValueGeneratedOnAdd()
                .HasColumnName("STT");

            entity.HasOne(d => d.IdKeHoachNavigation).WithMany(p => p.NvlKeHoachChiTiets)
                .HasForeignKey(d => d.IdKeHoach)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_KHSP_TD");
        });

        modelBuilder.Entity<NvlKeHoachGhiChu>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlKeHoachGhiChu");

            entity.Property(e => e.GhiChu).HasMaxLength(100);
            entity.Property(e => e.Ngay).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SerialKhsp).HasColumnName("SerialKHSP");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlKeHoachMuaHangItem>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlKeHoachMuaHangItem");

            entity.Property(e => e.DonGia).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.DuyetItemMsg).HasMaxLength(1000);
            entity.Property(e => e.Dvt)
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.GhiChu).HasMaxLength(100);
            entity.Property(e => e.HuyDatHang).HasMaxLength(100);
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.MaSp)
                .HasMaxLength(100)
                .HasColumnName("MaSP");
            entity.Property(e => e.NgayEdit)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SerialDn).HasColumnName("SerialDN");
            entity.Property(e => e.Slhuy)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("SLHuy");
            entity.Property(e => e.SlquyDoiSp)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("SLQuyDoiSP");
            entity.Property(e => e.SltheoDoi)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("SLTheoDoi");
            entity.Property(e => e.SoLuong).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.Stt)
                .HasDefaultValue(0)
                .HasColumnName("STT");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.TenLienKet).HasMaxLength(150);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.Vat).HasColumnName("VAT");

            entity.HasOne(d => d.MaHangNavigation).WithMany(p => p.NvlKeHoachMuaHangItems)
                .HasForeignKey(d => d.MaHang)
                .HasConstraintName("FK_NvlKeHoachMuaHangItem_NvlHangHoa");

            entity.HasOne(d => d.SerialDnNavigation).WithMany(p => p.NvlKeHoachMuaHangItems)
                .HasForeignKey(d => d.SerialDn)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_NvlKeHoachMuaHangItem_NvlKehoachMuaHang");
        });

        modelBuilder.Entity<NvlKeHoachMuaHangItemLog>(entity =>
        {
            entity.HasKey(e => e.Stt);

            entity.ToTable("NvlKeHoachMuaHangItem_Log");

            entity.Property(e => e.Stt).HasColumnName("STT");
            entity.Property(e => e.Dvt)
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.GhiChu).HasMaxLength(100);
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.MaSp)
                .HasMaxLength(100)
                .HasColumnName("MaSP");
            entity.Property(e => e.NgayInsert).HasColumnType("datetime");
            entity.Property(e => e.NgayUpdate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SerialDn).HasColumnName("SerialDN");
            entity.Property(e => e.SlquyDoiSp).HasColumnName("SLQuyDoiSP");
            entity.Property(e => e.SltheoDoi).HasColumnName("SLTheoDoi");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.UserUpdate).HasMaxLength(100);
            entity.Property(e => e.Vat).HasColumnName("VAT");
        });

        modelBuilder.Entity<NvlKeHoachSp>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_KHSP");

            entity.ToTable("NvlKeHoachSP");

            entity.Property(e => e.Id)
                .HasMaxLength(100)
                .HasColumnName("ID");
            entity.Property(e => e.ArticleNumber).HasMaxLength(100);
            entity.Property(e => e.ArticleNumberDm)
                .HasMaxLength(100)
                .HasColumnName("ArticleNumberDM");
            entity.Property(e => e.Cont)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DateFinishActive).HasColumnType("datetime");
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.KhuVuc)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.KyDuyet).HasMaxLength(100);
            entity.Property(e => e.MaKeHoach)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaMauKh)
                .HasMaxLength(100)
                .HasColumnName("MaMauKH");
            entity.Property(e => e.MaSp)
                .HasMaxLength(100)
                .HasColumnName("MaSP");
            entity.Property(e => e.Ngay).HasColumnType("datetime");
            entity.Property(e => e.NhaMay).HasMaxLength(100);
            entity.Property(e => e.Ponumber)
                .HasMaxLength(100)
                .HasColumnName("PONumber");
            entity.Property(e => e.SerialDn).HasColumnName("SerialDN");
            entity.Property(e => e.SerialKhthangItem).HasColumnName("SerialKHThangItem");
            entity.Property(e => e.SoLuongSp).HasColumnName("SoLuongSP");
            entity.Property(e => e.SoTtkh).HasColumnName("SoTTKH");
            entity.Property(e => e.Stt)
                .ValueGeneratedOnAdd()
                .HasColumnName("STT");
            entity.Property(e => e.TenKeHoach).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);

            entity.HasOne(d => d.SerialDnNavigation).WithMany(p => p.NvlKeHoachSps)
                .HasForeignKey(d => d.SerialDn)
                .HasConstraintName("FK_NvlKeHoachSP_NvlKehoachMuaHang");
        });

        modelBuilder.Entity<NvlKehoachMuaHang>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlKehoachMuaHang");

            entity.Property(e => e.BoPhanMuaHang).HasMaxLength(150);
            entity.Property(e => e.GhiChu).HasMaxLength(100);
            entity.Property(e => e.KhuVuc).HasMaxLength(100);
            entity.Property(e => e.LoaiKeHoach).HasMaxLength(100);
            entity.Property(e => e.LyDo).HasMaxLength(100);
            entity.Property(e => e.MaDn)
                .HasMaxLength(100)
                .HasColumnName("MaDN");
            entity.Property(e => e.NgayDn)
                .HasColumnType("date")
                .HasColumnName("NgayDN");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgayMax).HasColumnType("date");
            entity.Property(e => e.NguoiDn)
                .HasMaxLength(100)
                .HasColumnName("NguoiDN");
            entity.Property(e => e.NhaMay).HasMaxLength(100);
            entity.Property(e => e.NoiDung).HasMaxLength(2000);
            entity.Property(e => e.NoiDungDeNghi).HasMaxLength(1500);
            entity.Property(e => e.PhongBan).HasMaxLength(100);
            entity.Property(e => e.Stt).HasColumnName("STT");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlKhachHang>(entity =>
        {
            entity.HasKey(e => e.MaKh).HasName("PK_KhachHang");

            entity.ToTable("NvlKhachHang");

            entity.Property(e => e.MaKh)
                .HasMaxLength(100)
                .HasColumnName("MaKH");
            entity.Property(e => e.DaiDienPl)
                .HasMaxLength(100)
                .HasColumnName("DaiDienPL");
            entity.Property(e => e.DiDong).HasMaxLength(100);
            entity.Property(e => e.DiaChi).HasMaxLength(1000);
            entity.Property(e => e.DienThoaiBan).HasMaxLength(100);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.LoaiHinhKinhDoanh).HasMaxLength(100);
            entity.Property(e => e.MaChungChi).HasMaxLength(100);
            entity.Property(e => e.MaNganHang).HasMaxLength(100);
            entity.Property(e => e.MaSoThue)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgaySoatXet).HasColumnType("date");
            entity.Property(e => e.NguoiSoatXet).HasMaxLength(100);
            entity.Property(e => e.NhomKh)
                .HasMaxLength(100)
                .HasColumnName("NhomKH");
            entity.Property(e => e.NhomMatHang).HasMaxLength(200);
            entity.Property(e => e.QuocGia).HasMaxLength(100);
            entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            entity.Property(e => e.SoTk)
                .HasMaxLength(100)
                .HasColumnName("SoTK");
            entity.Property(e => e.SwiftCode).HasMaxLength(100);
            entity.Property(e => e.TenKh)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("TenKH");
            entity.Property(e => e.TenTk)
                .HasMaxLength(150)
                .HasColumnName("TenTK");
            entity.Property(e => e.TinhThanh).HasMaxLength(100);
            entity.Property(e => e.TinhTrang).HasMaxLength(100);
            entity.Property(e => e.TinhTrangThue).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.Website).HasMaxLength(500);
        });

        modelBuilder.Entity<NvlKhuVuc>(entity =>
        {
            entity.HasKey(e => e.MaKhuVuc);

            entity.ToTable("NvlKhuVuc");

            entity.Property(e => e.MaKhuVuc).HasMaxLength(100);
            entity.Property(e => e.IconMaterial).HasMaxLength(50);
            entity.Property(e => e.KhtheoNhaMay)
                .HasMaxLength(100)
                .HasColumnName("KHTheoNhaMay");
            entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            entity.Property(e => e.Stt).HasColumnName("STT");
            entity.Property(e => e.TenKhuVuc).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlKyDuyet>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlKyDuyet");

            entity.Property(e => e.DaDuyet).HasMaxLength(100);
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.LoaiDuyet).HasMaxLength(100);
            entity.Property(e => e.NgayApDung).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgayKyDuyet).HasColumnType("datetime");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.UserDuyet).HasMaxLength(100);
            entity.Property(e => e.UserYeuCau).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlKyDuyetHanMuc>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlKyDuyetHanMuc");

            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.UserName).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlKyDuyetItem>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlKyDuyetItem");

            entity.Property(e => e.GhiChu).HasMaxLength(300);
            entity.Property(e => e.LoaiDuyet).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.UserDuyet).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlLienKetDhmua>(entity =>
        {
            entity.HasKey(e => e.TenLienKet).HasName("PK_NvlLienKetDHMua_1");

            entity.ToTable("NvlLienKetDHMua");

            entity.Property(e => e.TenLienKet).HasMaxLength(100);
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.MaDhmua)
                .HasMaxLength(100)
                .HasColumnName("MaDHMua");
            entity.Property(e => e.MaSp)
                .HasMaxLength(100)
                .HasColumnName("MaSP");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlMaKho>(entity =>
        {
            entity.HasKey(e => e.MaKho);

            entity.ToTable("NvlMaKho");

            entity.HasIndex(e => e.MaKho, "UQ__MaKho__3BDA9351227387EF").IsUnique();

            entity.Property(e => e.MaKho).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            entity.Property(e => e.TenKho).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlMaMau>(entity =>
        {
            entity.HasKey(e => e.MaMau).HasName("PK_MaMau");

            entity.ToTable("NvlMaMau");

            entity.Property(e => e.MaMau).HasMaxLength(100);
            entity.Property(e => e.Colorhex).HasMaxLength(50);
            entity.Property(e => e.Colorint).HasMaxLength(50);
            entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            entity.Property(e => e.TenMau).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlMsgManage>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlMsgManage");

            entity.Property(e => e.MsgReply).HasMaxLength(1000);
            entity.Property(e => e.MsgWait).HasMaxLength(500);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgayReply).HasColumnType("datetime");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.UserReply).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNghiemThuBienBan>(entity =>
        {
            entity.HasKey(e => e.Serial).HasName("PK_Nvl_BienBanNghiemThu");

            entity.ToTable("NvlNghiemThuBienBan");

            entity.Property(e => e.Active).HasDefaultValue(1);
            entity.Property(e => e.BieuMau).HasMaxLength(100);
            entity.Property(e => e.MauBbin)
                .HasMaxLength(100)
                .HasColumnName("MauBBIn");
            entity.Property(e => e.NgayBanHanh).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TenBb)
                .HasMaxLength(200)
                .HasColumnName("TenBB");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNghiemThuBienBanItem>(entity =>
        {
            entity.HasKey(e => e.Serial).HasName("PK_NvlBienBanNghiemThuItem");

            entity.ToTable("NvlNghiemThuBienBanItem");

            entity.Property(e => e.CapDoKt)
                .HasMaxLength(100)
                .HasColumnName("CapDoKT");
            entity.Property(e => e.DanhMuc).HasMaxLength(500);
            entity.Property(e => e.DienGiai).HasMaxLength(1000);
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.HangMuc).HasMaxLength(100);
            entity.Property(e => e.LoaiLoi).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NhomDanhMuc).HasMaxLength(200);
            entity.Property(e => e.PathImg).HasMaxLength(500);
            entity.Property(e => e.SerialBb).HasColumnName("SerialBB");
            entity.Property(e => e.Stt).HasColumnName("STT");
            entity.Property(e => e.TieuChuanYeuCau).HasMaxLength(1000);
            entity.Property(e => e.UserInsert).HasMaxLength(100);

            entity.HasOne(d => d.SerialBbNavigation).WithMany(p => p.NvlNghiemThuBienBanItems)
                .HasForeignKey(d => d.SerialBb)
                .HasConstraintName("FK_NvlNghiemThuBienBanItem_NvlNghiemThuBienBan");
        });

        modelBuilder.Entity<NvlNghiemThuDienGiai>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlNghiemThuDienGiai");

            entity.Property(e => e.ChuThich).HasMaxLength(2000);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SerialBb).HasColumnName("SerialBB");
            entity.Property(e => e.Stt).HasColumnName("STT");
            entity.Property(e => e.UserInsert).HasMaxLength(100);

            entity.HasOne(d => d.SerialBbNavigation).WithMany(p => p.NvlNghiemThuDienGiais)
                .HasForeignKey(d => d.SerialBb)
                .HasConstraintName("FK_NvlNghiemThuDienGiai_NvlNghiemThuBienBan");
        });

        modelBuilder.Entity<NvlNghiemThuHangMucDienGiai>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlNghiemThuHangMucDienGiai");

            entity.Property(e => e.DienGiai).HasMaxLength(2000);
            entity.Property(e => e.HangMuc).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SerialBb).HasColumnName("SerialBB");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNghiemThuItem>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlNghiemThuItem");

            entity.Property(e => e.CapDoKt)
                .HasMaxLength(100)
                .HasColumnName("CapDoKT");
            entity.Property(e => e.DienGiai).HasMaxLength(200);
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.KetLuan).HasMaxLength(200);
            entity.Property(e => e.NgayGioBatDau).HasColumnType("datetime");
            entity.Property(e => e.NgayGioKetThuc).HasColumnType("datetime");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SerialBbitem).HasColumnName("SerialBBItem");
            entity.Property(e => e.SerialNt).HasColumnName("SerialNT");
            entity.Property(e => e.Slloi).HasColumnName("SLLoi");
            entity.Property(e => e.Slmau).HasColumnName("SLMau");
            entity.Property(e => e.SlthucTe).HasColumnName("SLThucTe");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNghiemThuMaster>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlNghiemThuMaster");

            entity.Property(e => e.DauTuan).HasMaxLength(100);
            entity.Property(e => e.DiaDiemNhap).HasMaxLength(100);
            entity.Property(e => e.Dvt)
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.HieuLucGiayCn)
                .HasMaxLength(100)
                .HasColumnName("HieuLucGiayCN");
            entity.Property(e => e.HieuLucTest).HasMaxLength(100);
            entity.Property(e => e.IdgroupBb).HasColumnName("IDGroupBB");
            entity.Property(e => e.KetLuanBb)
                .HasMaxLength(100)
                .HasColumnName("KetLuanBB");
            entity.Property(e => e.LoPhuKien).HasMaxLength(100);
            entity.Property(e => e.LoSanXuat).HasMaxLength(100);
            entity.Property(e => e.LoaiVatTu).HasMaxLength(100);
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.MaNcc)
                .HasMaxLength(100)
                .HasColumnName("MaNCC");
            entity.Property(e => e.MaSp)
                .HasMaxLength(100)
                .HasColumnName("MaSP");
            entity.Property(e => e.NgayHangVe).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgayKiemTra).HasColumnType("date");
            entity.Property(e => e.NgayNhapKho).HasColumnType("date");
            entity.Property(e => e.NhaMay).HasMaxLength(100);
            entity.Property(e => e.SerialBb).HasColumnName("SerialBB");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.Tem).HasMaxLength(100);
            entity.Property(e => e.ToKhai).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNghiemThuSettingColumn>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SerialBb).HasColumnName("SerialBB");
            entity.Property(e => e.SerialBbitem).HasColumnName("SerialBBItem");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNghiemThuTieuChuan>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlNghiemThuTieuChuan");

            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SlchapNhan).HasColumnName("SLChapNhan");
            entity.Property(e => e.Slin)
                .HasMaxLength(200)
                .HasColumnName("SLin");
            entity.Property(e => e.Slmau).HasColumnName("SLMau");
            entity.Property(e => e.Slmax).HasColumnName("SLMax");
            entity.Property(e => e.Slmin).HasColumnName("SLMin");
            entity.Property(e => e.TieuChuan).HasMaxLength(150);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNhaCungCap>(entity =>
        {
            entity.HasKey(e => e.MaNcc).HasName("PK_NhaCungCap");

            entity.ToTable("NvlNhaCungCap");

            entity.Property(e => e.MaNcc)
                .HasMaxLength(100)
                .HasColumnName("MaNCC");
            entity.Property(e => e.DaiDienPl)
                .HasMaxLength(100)
                .HasColumnName("DaiDienPL");
            entity.Property(e => e.DiDong).HasMaxLength(100);
            entity.Property(e => e.DiaChi).HasMaxLength(1000);
            entity.Property(e => e.DienThoaiBan).HasMaxLength(100);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.LoaiHinhKinhDoanh).HasMaxLength(100);
            entity.Property(e => e.MaChungChi).HasMaxLength(100);
            entity.Property(e => e.MaNganHang).HasMaxLength(100);
            entity.Property(e => e.MaSoThue).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgaySoatXet).HasColumnType("date");
            entity.Property(e => e.NguoiSoatXet).HasMaxLength(100);
            entity.Property(e => e.NhomMatHang).HasMaxLength(200);
            entity.Property(e => e.NhomNcc)
                .HasMaxLength(100)
                .HasColumnName("NhomNCC");
            entity.Property(e => e.QuocGia).HasMaxLength(100);
            entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            entity.Property(e => e.SoTk)
                .HasMaxLength(100)
                .HasColumnName("SoTK");
            entity.Property(e => e.SwiftCode).HasMaxLength(100);
            entity.Property(e => e.TenNcc)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("TenNCC");
            entity.Property(e => e.TenTk)
                .HasMaxLength(150)
                .HasColumnName("TenTK");
            entity.Property(e => e.TinhThanh).HasMaxLength(100);
            entity.Property(e => e.TinhTrang).HasMaxLength(100);
            entity.Property(e => e.TinhTrangThue).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.Website).HasMaxLength(500);
        });

        modelBuilder.Entity<NvlNhaCungCapHd>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlNhaCungCapHD");

            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.HanThanhToan).HasMaxLength(200);
            entity.Property(e => e.MaNcc)
                .HasMaxLength(100)
                .HasColumnName("MaNCC");
            entity.Property(e => e.NgayHieuLuc).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SoHd)
                .HasMaxLength(100)
                .HasColumnName("SoHD");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNhapXuat>(entity =>
        {
            entity.HasKey(e => e.Serial).HasName("PK_CTKH");

            entity.ToTable("NvlNhapXuat");

            entity.Property(e => e.DienGiai).HasMaxLength(200);
            entity.Property(e => e.Flag)
                .HasDefaultValue(0)
                .HasColumnName("flag");
            entity.Property(e => e.GhiChu).HasMaxLength(250);
            entity.Property(e => e.LyDo).HasMaxLength(100);
            entity.Property(e => e.MaCt)
                .HasMaxLength(50)
                .HasColumnName("MaCT");
            entity.Property(e => e.MaDn)
                .HasMaxLength(100)
                .HasColumnName("MaDN");
            entity.Property(e => e.MaGn)
                .HasMaxLength(100)
                .HasColumnName("MaGN");
            entity.Property(e => e.MaKho).HasMaxLength(100);
            entity.Property(e => e.Ngay).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NghiemThu)
                .HasMaxLength(100)
                .HasDefaultValue("Chưa nghiệm thu");
            entity.Property(e => e.NguoiDn)
                .HasMaxLength(100)
                .HasColumnName("NguoiDN");
            entity.Property(e => e.NhaMay).HasMaxLength(100);
            entity.Property(e => e.Ponumber)
                .HasMaxLength(100)
                .HasColumnName("PONumber");
            entity.Property(e => e.Sttct).HasColumnName("STTCT");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNhapXuatItem>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlNhapXuatItem");

            entity.Property(e => e.ArticleNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Barcode).HasMaxLength(100);
            entity.Property(e => e.DauTuan).HasMaxLength(100);
            entity.Property(e => e.DonGia).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.Dvt)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.Dvttt)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("DVTTT");
            entity.Property(e => e.Flag)
                .HasDefaultValue(0)
                .HasColumnName("flag");
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.KhachHangXuatXu)
                .HasMaxLength(100)
                .HasColumnName("KhachHang_XuatXu");
            entity.Property(e => e.MaHang)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaKien).HasMaxLength(100);
            entity.Property(e => e.MaSp)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("MaSP");
            entity.Property(e => e.NgayHetHan).HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgaySanXuat).HasColumnType("date");
            entity.Property(e => e.SerialCt).HasColumnName("SerialCT");
            entity.Property(e => e.SerialKhdh).HasColumnName("SerialKHDH");
            entity.Property(e => e.Slnhap)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("SLNhap");
            entity.Property(e => e.SlnhapTt)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("SLNhapTT");
            entity.Property(e => e.Slxuat)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("SLXuat");
            entity.Property(e => e.SlxuatTt)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("SLXuatTT");
            entity.Property(e => e.SoLo).HasMaxLength(100);
            entity.Property(e => e.SoXe).HasMaxLength(20);
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.ViTri).HasMaxLength(100);

            entity.HasOne(d => d.MaHangNavigation).WithMany(p => p.NvlNhapXuatItems)
                .HasForeignKey(d => d.MaHang)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NvlNhapXuatItem_NvlHangHoa");

            entity.HasOne(d => d.SerialCtNavigation).WithMany(p => p.NvlNhapXuatItems)
                .HasForeignKey(d => d.SerialCt)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NvlNhapXuatItem_NvlNhapXuat");
        });

        modelBuilder.Entity<NvlNhapXuatItemLog>(entity =>
        {
            entity.HasKey(e => e.Stt);

            entity.ToTable("NvlNhapXuatItem_Log");

            entity.Property(e => e.Stt).HasColumnName("STT");
            entity.Property(e => e.ArticleNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Barcode).HasMaxLength(100);
            entity.Property(e => e.DauTuan).HasMaxLength(100);
            entity.Property(e => e.Dvt)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("DVT");
            entity.Property(e => e.Dvttt)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("DVTTT");
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.KhachHangXuatXu)
                .HasMaxLength(100)
                .HasColumnName("KhachHang_XuatXu");
            entity.Property(e => e.LyDoUpdate).HasMaxLength(200);
            entity.Property(e => e.MaHang)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaKien).HasMaxLength(100);
            entity.Property(e => e.MaSp)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("MaSP");
            entity.Property(e => e.NgayHetHan).HasColumnType("date");
            entity.Property(e => e.NgayInsert).HasColumnType("datetime");
            entity.Property(e => e.NgayUpdate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SerialCt).HasColumnName("SerialCT");
            entity.Property(e => e.SerialKhdh).HasColumnName("SerialKHDH");
            entity.Property(e => e.Slnhap).HasColumnName("SLNhap");
            entity.Property(e => e.SlnhapTt).HasColumnName("SLNhapTT");
            entity.Property(e => e.Slxuat).HasColumnName("SLXuat");
            entity.Property(e => e.SlxuatTt).HasColumnName("SLXuatTT");
            entity.Property(e => e.SoLo).HasMaxLength(100);
            entity.Property(e => e.SoXe).HasMaxLength(20);
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.UserUpdate).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNhapXuatLyDo>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlNhapXuat_LyDo");

            entity.Property(e => e.LyDo)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.MaLyDo).HasMaxLength(100);
            entity.Property(e => e.Tag).HasMaxLength(200);
        });

        modelBuilder.Entity<NvlNhomHang>(entity =>
        {
            entity.HasKey(e => e.MaNhom).HasName("PK_NhomHang_1");

            entity.ToTable("NvlNhomHang");

            entity.Property(e => e.MaNhom).HasMaxLength(100);
            entity.Property(e => e.HuongDan).HasMaxLength(2000);
            entity.Property(e => e.KeySearch).HasMaxLength(1000);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PhanLoai)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            entity.Property(e => e.TenNhom)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlNoiBo>(entity =>
        {
            entity.HasKey(e => e.MaNb).HasName("PK_NoiBo");

            entity.ToTable("NvlNoiBo");

            entity.Property(e => e.MaNb)
                .HasMaxLength(100)
                .HasColumnName("MaNB");
            entity.Property(e => e.DaiDienPl)
                .HasMaxLength(100)
                .HasColumnName("DaiDienPL");
            entity.Property(e => e.DiDong).HasMaxLength(100);
            entity.Property(e => e.DiaChi).HasMaxLength(1000);
            entity.Property(e => e.DienThoaiBan).HasMaxLength(100);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.LoaiHinhKinhDoanh).HasMaxLength(100);
            entity.Property(e => e.MaChungChi).HasMaxLength(100);
            entity.Property(e => e.MaNganHang).HasMaxLength(100);
            entity.Property(e => e.MaSoThue).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgaySoatXet).HasColumnType("date");
            entity.Property(e => e.NguoiSoatXet).HasMaxLength(100);
            entity.Property(e => e.NhomMatHang).HasMaxLength(200);
            entity.Property(e => e.NhomNb)
                .HasMaxLength(100)
                .HasColumnName("NhomNB");
            entity.Property(e => e.QuocGia).HasMaxLength(100);
            entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            entity.Property(e => e.SoTk)
                .HasMaxLength(100)
                .HasColumnName("SoTK");
            entity.Property(e => e.SwiftCode).HasMaxLength(100);
            entity.Property(e => e.TenNb)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("TenNB");
            entity.Property(e => e.TenTk)
                .HasMaxLength(150)
                .HasColumnName("TenTK");
            entity.Property(e => e.TinhThanh).HasMaxLength(100);
            entity.Property(e => e.TinhTrang).HasMaxLength(100);
            entity.Property(e => e.TinhTrangThue).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.Website).HasMaxLength(500);
        });

        modelBuilder.Entity<NvlReportDetail>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlReportDetail");

            entity.Property(e => e.NameReport).HasMaxLength(100);
            entity.Property(e => e.NameRp).HasMaxLength(100);
            entity.Property(e => e.ShowNameRp).HasMaxLength(1000);
            entity.Property(e => e.Stt).HasColumnName("STT");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.TextRp).HasMaxLength(2000);
            entity.Property(e => e.TypeRecent).HasMaxLength(100);
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlSoDoKho>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlSoDoKho");

            entity.HasIndex(e => new { e.ViTri, e.NhaMay, e.MaKho }, "uniqueSoDo").IsUnique();

            entity.Property(e => e.Day).HasMaxLength(10);
            entity.Property(e => e.Hang).HasMaxLength(20);
            entity.Property(e => e.Ke).HasMaxLength(10);
            entity.Property(e => e.MaKho).HasMaxLength(100);
            entity.Property(e => e.NhaMay).HasMaxLength(50);
            entity.Property(e => e.Pallet).HasMaxLength(10);
            entity.Property(e => e.Tang).HasMaxLength(10);
            entity.Property(e => e.ViTri)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<NvlThanhToan>(entity =>
        {
            entity.HasKey(e => e.Serial).HasName("PK_ThanhToan");

            entity.ToTable("NvlThanhToan");

            entity.Property(e => e.DienGiai).HasMaxLength(100);
            entity.Property(e => e.Flag).HasColumnName("flag");
            entity.Property(e => e.LyDo).HasMaxLength(100);
            entity.Property(e => e.MaCttt)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("MaCTTT");
            entity.Property(e => e.MaKn)
                .HasMaxLength(100)
                .HasColumnName("MaKN");
            entity.Property(e => e.Ngay)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NgayXacNhan).HasColumnType("datetime");
            entity.Property(e => e.NguoiXacNhan).HasMaxLength(100);
            entity.Property(e => e.NoiTt)
                .HasMaxLength(100)
                .HasColumnName("NoiTT");
            entity.Property(e => e.SignType).HasColumnName("sign_type");
            entity.Property(e => e.Type).HasColumnName("type_");
            entity.Property(e => e.UserIns).HasMaxLength(100);
            entity.Property(e => e.UserUp).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlThanhToanItem>(entity =>
        {
            entity.HasKey(e => e.Serial).HasName("PK_ChiTietCTTT");

            entity.ToTable("NvlThanhToanItem");

            entity.Property(e => e.MaCt).HasColumnName("MaCT");
            entity.Property(e => e.MaTt).HasColumnName("MaTT");
            entity.Property(e => e.NgayInsert).HasColumnType("datetime");
            entity.Property(e => e.SoTien).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
        });

        modelBuilder.Entity<NvlViTri>(entity =>
        {
            entity.HasKey(e => e.Serial);

            entity.ToTable("NvlViTri");

            entity.Property(e => e.GroupPallet).HasMaxLength(100);
            entity.Property(e => e.MaHang).HasMaxLength(100);
            entity.Property(e => e.MaKho).HasMaxLength(100);
            entity.Property(e => e.NgayInsert)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NhaMay).HasMaxLength(100);
            entity.Property(e => e.SerialNk).HasColumnName("SerialNK");
            entity.Property(e => e.UserInsert).HasMaxLength(100);
            entity.Property(e => e.ViTri).HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}