// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlChiTietKhuVuc
{
    public int Serial { get; set; }

    public string MaSp { get; set; }

    public double SlquyDoi { get; set; }

    public string MaHang { get; set; }

    public string KhuVuc { get; set; }

    public string ArticleNumber { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public string ChatLuong { get; set; }

    public double DinhMucHaoHut { get; set; }

    public DateTime? NgayInsert { get; set; }

    public virtual NvlHangHoa MaHangNavigation { get; set; }
}