// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlDonDatHangItem
{
    public int Serial { get; set; }

    public int? SerialMaDh { get; set; }

    public string MaHang { get; set; }

    public decimal SldatHang { get; set; }

    public decimal SltheoDoi { get; set; }

    public string Dvt { get; set; }

    public decimal? DonGia { get; set; }

    public int? SerialLink { get; set; }

    public string TableName { get; set; }

    public string MaNcc { get; set; }

    public DateTime? NgayDknhapKho { get; set; }

    public DateTime? NgayEdit { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public int? GiaTri { get; set; }

    public string DienGiai { get; set; }

    public string DuyetItemMsg { get; set; }

    public int? Stt { get; set; }

    public decimal? Slhuy { get; set; }

    public string KeyGroup { get; set; }

    public virtual NvlNhaCungCap MaNccNavigation { get; set; }

    public virtual NvlDonDatHang SerialMaDhNavigation { get; set; }
}