// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlDonDatHangFileAttach
{
    public int Serial { get; set; }

    public int? SerialDatHang { get; set; }

    public string NoiDung { get; set; }

    public string UrlFile { get; set; }

    public double? FileSize { get; set; }

    public DateTime? NgayUpload { get; set; }

    public string UserInsert { get; set; }

    public string UserUpload { get; set; }

    public string TableName { get; set; }

    public DateTime? NgayInsert { get; set; }
}