// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlDuyetGium
{
    public int Serial { get; set; }

    public int? Stt { get; set; }

    public string MaDn { get; set; }

    public string NguoiDn { get; set; }

    public string LoaiDuyetGia { get; set; }

    public string Dvt { get; set; }

    public string LyDo { get; set; }

    public string PhongBan { get; set; }

    public string NhaMay { get; set; }

    public string DuAnHanMuc { get; set; }

    public string CuocVanChuyen { get; set; }

    public string ThueGtgt { get; set; }

    public string KetQua { get; set; }

    public string ChonNhaCungCap { get; set; }

    public string UserInsert { get; set; }

    public DateTime? Ngay { get; set; }

    public string GhiChu { get; set; }

    public DateTime? NgayApDung { get; set; }

    public DateTime? NgayKetThuc { get; set; }

    public DateTime? NgayInsert { get; set; }
}