// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlDonDatHang
{
    public int Serial { get; set; }

    public string MaDatHang { get; set; }

    public string PhongBan { get; set; }

    public int? Sttdh { get; set; }

    public DateTime? NgayTao { get; set; }

    public DateTime? NgayDatHang { get; set; }

    public DateTime? NgayMax { get; set; }

    public string KhuVuc { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public string Dvtt { get; set; }

    public DateTime? NgayInsert { get; set; }

    public int? Active { get; set; }

    public string NoiDungDeNghi { get; set; }

    public int? Sttdhncc { get; set; }

    public string MaNcc { get; set; }

    public string SoHd { get; set; }

    public string LoaiDonHang { get; set; }

    public virtual ICollection<NvlDonDatHangChiPhiKhac> NvlDonDatHangChiPhiKhacs { get; set; } = new List<NvlDonDatHangChiPhiKhac>();

    public virtual ICollection<NvlDonDatHangItem> NvlDonDatHangItems { get; set; } = new List<NvlDonDatHangItem>();
}