// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlDuyetGiaItem
{
    public int Serial { get; set; }

    public int? Stt { get; set; }

    public int? SerialLink { get; set; }

    public string KeyGroup { get; set; }

    public string TableName { get; set; }

    public string MaHang { get; set; }

    public string XuatXu { get; set; }

    public string Dvt { get; set; }

    public decimal? SlduToan { get; set; }

    public decimal? DonGiaTheoDvt { get; set; }

    public decimal? DonGiaDuyet { get; set; }

    public string MaNccduyet { get; set; }

    public string NhaCungCapDuyet { get; set; }

    public decimal? GiaDangMua { get; set; }

    public string GhiChu { get; set; }

    public decimal? DinhMuc { get; set; }

    public string TinhTrangDuyet { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public string MsgKhongDuyet { get; set; }
}