// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlDonDatHangChiPhiKhac
{
    public int Serial { get; set; }

    public int? SerialDatHang { get; set; }

    public double DonGia { get; set; }

    public double SoLuong { get; set; }

    public int SignInt { get; set; }

    public string NoiDung { get; set; }

    public string Dvt { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public virtual NvlDonDatHang SerialDatHangNavigation { get; set; }
}