// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlGhiNoHieuChinh
{
    public int Serial { get; set; }

    public string MaHang { get; set; }

    public double? SoLuong { get; set; }

    public string LyDo { get; set; }

    public string UserInsert { get; set; }

    public string TableName { get; set; }

    public string GhiChu { get; set; }

    public string MaKho { get; set; }

    public string NhaMay { get; set; }

    public DateTime? NgayInsert { get; set; }
}