// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlHangHoaDungChungItem
{
    public int Serial { get; set; }

    public int SerialGroup { get; set; }

    public string MaHang { get; set; }

    public double SlquyDoi { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public virtual NvlHangHoaDungChungGroup SerialGroupNavigation { get; set; }
}