// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlHangHoa
{
    public int Serial { get; set; }

    public string MaHang { get; set; }

    public string TenHang { get; set; }

    public string QuyCach { get; set; }

    public string MaNhom { get; set; }

    public string Dvt { get; set; }

    public string ChatLuong { get; set; }

    public string PhanLoaiDm { get; set; }

    public double? MinTk { get; set; }

    public double? MaxTk { get; set; }

    public string UserInsert { get; set; }

    public int? Flag { get; set; }

    public string GhiChu { get; set; }

    public string MaPdoc { get; set; }

    public string MaKhac { get; set; }

    public string MaSpgroup { get; set; }

    public string TenSppdoc { get; set; }

    public string MaMau { get; set; }

    public double? TyLeHaoHut { get; set; }

    public string KeySearch { get; set; }

    public string PathImg { get; set; }

    public double? Slcont { get; set; }

    public DateTime? NgayInsert { get; set; }

    public string TrangThai { get; set; }

    public string XuatXu { get; set; }

    public virtual NvlNhomHang MaNhomNavigation { get; set; }

    public virtual ICollection<NvlChiTietKhuVuc> NvlChiTietKhuVucs { get; set; } = new List<NvlChiTietKhuVuc>();

    public virtual ICollection<NvlInPhieu> NvlInPhieus { get; set; } = new List<NvlInPhieu>();

    public virtual ICollection<NvlKeHoachMuaHangItem> NvlKeHoachMuaHangItems { get; set; } = new List<NvlKeHoachMuaHangItem>();

    public virtual ICollection<NvlNhapXuatItem> NvlNhapXuatItems { get; set; } = new List<NvlNhapXuatItem>();
}