// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlHangHoaDvtquyDoi
{
    public int Serial { get; set; }

    public string MaHang { get; set; }

    public string Dvt1 { get; set; }

    public string Dvt2 { get; set; }

    public double? QuyDoi { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }
}