// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlInPhieu
{
    public int Serial { get; set; }

    public int? SerialCt { get; set; }

    public int MaCt { get; set; }

    public string MaHang { get; set; }

    public string Dvt { get; set; }

    public double? SoLuong { get; set; }

    public string KhachHangXuatXu { get; set; }

    public DateTime? NgayHetHan { get; set; }

    public string MaKien { get; set; }

    public string SoLo { get; set; }

    public string SoXe { get; set; }

    public string GhiChu { get; set; }

    public string Barcode { get; set; }

    public string MaSp { get; set; }

    public string ArticleNumber { get; set; }

    public string KhuVuc { get; set; }

    public string ChatLuong { get; set; }

    public int? CheckPrint { get; set; }

    public string DauTuan { get; set; }

    public DateTime? NgaySanXuat { get; set; }

    public string MaGn { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public virtual NvlHangHoa MaHangNavigation { get; set; }
}