// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlKeHoachChiTiet
{
    public int Stt { get; set; }

    public string Id { get; set; }

    public string IdKeHoach { get; set; }

    public string MaHang { get; set; }

    public double? Slkh { get; set; }

    public double? SltheoDoi { get; set; }

    public int? DuPhong { get; set; }

    public DateTime? Ngay { get; set; }

    public string NhaMay { get; set; }

    public string ArticleNumber { get; set; }

    public double? DinhMucHaoHut { get; set; }

    public virtual NvlKeHoachSp IdKeHoachNavigation { get; set; }
}