// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlKehoachMuaHang
{
    public int Serial { get; set; }

    public int? Stt { get; set; }

    public string MaDn { get; set; }

    public string NguoiDn { get; set; }

    public string LyDo { get; set; }

    public string KhuVuc { get; set; }

    public DateTime? NgayDn { get; set; }

    public string PhongBan { get; set; }

    public string NhaMay { get; set; }

    public DateTime? NgayMax { get; set; }

    public string NoiDung { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public string LoaiKeHoach { get; set; }

    public DateTime? NgayInsert { get; set; }

    public string NoiDungDeNghi { get; set; }

    public string BoPhanMuaHang { get; set; }

    public virtual ICollection<NvlKeHoachMuaHangItem> NvlKeHoachMuaHangItems { get; set; } = new List<NvlKeHoachMuaHangItem>();

    public virtual ICollection<NvlKeHoachSp> NvlKeHoachSps { get; set; } = new List<NvlKeHoachSp>();
}