// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlKeHoachGhiChu
{
    public int Serial { get; set; }

    public int? SerialKhsp { get; set; }

    public string TableName { get; set; }

    public DateTime? Ngay { get; set; }

    public double? SoLuong { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }
}