// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlKeHoachMuaHangItem
{
    public int Serial { get; set; }

    public int? SerialDn { get; set; }

    public string MaHang { get; set; }

    public decimal? SoLuong { get; set; }

    public decimal? SltheoDoi { get; set; }

    public decimal? DonGia { get; set; }

    public string Dvt { get; set; }

    public int? Vat { get; set; }

    public string GhiChu { get; set; }

    public string MaSp { get; set; }

    public int? SerialLink { get; set; }

    public string TableName { get; set; }

    public decimal? SlquyDoiSp { get; set; }

    public DateTime? NgayEdit { get; set; }

    public DateTime? NgayInsert { get; set; }

    public string UserInsert { get; set; }

    public int? DuyetItem { get; set; }

    public string DuyetItemMsg { get; set; }

    public int? Stt { get; set; }

    public string HuyDatHang { get; set; }

    public string TenLienKet { get; set; }

    public decimal? Slhuy { get; set; }

    public virtual NvlHangHoa MaHangNavigation { get; set; }

    public virtual NvlKehoachMuaHang SerialDnNavigation { get; set; }
}