// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlKhuVuc
{
    public int Serial { get; set; }

    public string MaKhuVuc { get; set; }

    public string TenKhuVuc { get; set; }

    public string IconMaterial { get; set; }

    public int? Stt { get; set; }

    public string KhtheoNhaMay { get; set; }
}