// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlKeHoachMuaHangItemLog
{
    public int Stt { get; set; }

    public int Serial { get; set; }

    public int? SerialDn { get; set; }

    public string MaHang { get; set; }

    public double? SoLuong { get; set; }

    public double? SltheoDoi { get; set; }

    public double? DonGia { get; set; }

    public string Dvt { get; set; }

    public int? Vat { get; set; }

    public string GhiChu { get; set; }

    public string MaSp { get; set; }

    public int? SerialLink { get; set; }

    public string TableName { get; set; }

    public double? SlquyDoiSp { get; set; }

    public DateTime? NgayInsert { get; set; }

    public string UserInsert { get; set; }

    public string UserUpdate { get; set; }

    public DateTime? NgayUpdate { get; set; }
}