// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlKyDuyet
{
    public int Serial { get; set; }

    public int? SerialLink { get; set; }

    public string TableName { get; set; }

    public string UserYeuCau { get; set; }

    public string UserDuyet { get; set; }

    public string LoaiDuyet { get; set; }

    public DateTime? NgayApDung { get; set; }

    public DateTime? NgayKyDuyet { get; set; }

    public DateTime? NgayInsert { get; set; }

    public string DaDuyet { get; set; }

    public string GhiChu { get; set; }
}