// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlKyDuyetHanMuc
{
    public int Serial { get; set; }

    public string UserName { get; set; }

    public long? HanMuc { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }
}