// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlKyDuyetItem
{
    public int Serial { get; set; }

    public int? SerialLinkMaster { get; set; }

    public int? SerialLinkItem { get; set; }

    public string TableName { get; set; }

    public string UserDuyet { get; set; }

    public string LoaiDuyet { get; set; }

    public string GhiChu { get; set; }

    public DateTime? NgayInsert { get; set; }
}