// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlLienKetDhmua
{
    public int Serial { get; set; }

    public string MaDhmua { get; set; }

    public string MaSp { get; set; }

    public string TenLienKet { get; set; }

    public double? SoLuong { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }
}