// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlMaMau
{
    public int Serial { get; set; }

    public string MaMau { get; set; }

    public string TenMau { get; set; }

    public string Colorint { get; set; }

    public string Colorhex { get; set; }
}