// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlMsgManage
{
    public int Serial { get; set; }

    public int? SerialLink { get; set; }

    public string TableName { get; set; }

    public string MsgWait { get; set; }

    public string MsgReply { get; set; }

    public string UserInsert { get; set; }

    public string UserReply { get; set; }

    public DateTime? NgayInsert { get; set; }

    public DateTime? NgayReply { get; set; }
}