// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNghiemThuDienGiai
{
    public int Serial { get; set; }

    public int? SerialBb { get; set; }

    public int? Stt { get; set; }

    public string ChuThich { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public virtual NvlNghiemThuBienBan SerialBbNavigation { get; set; }
}