// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNhaCungCapHd
{
    public int Serial { get; set; }

    public string MaNcc { get; set; }

    public string SoHd { get; set; }

    public DateTime? NgayHieuLuc { get; set; }

    public string HanThanhToan { get; set; }

    public string UserInsert { get; set; }

    public string GhiChu { get; set; }

    public DateTime? NgayInsert { get; set; }
}