// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNghiemThuBienBanItem
{
    public int Serial { get; set; }

    public int? SerialBb { get; set; }

    public int? Stt { get; set; }

    public string HangMuc { get; set; }

    public string NhomDanhMuc { get; set; }

    public string DanhMuc { get; set; }

    public string TieuChuanYeuCau { get; set; }

    public string CapDoKt { get; set; }

    public string PathImg { get; set; }

    public string DienGiai { get; set; }

    public string LoaiLoi { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public virtual NvlNghiemThuBienBan SerialBbNavigation { get; set; }
}