// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNhapXuat
{
    public int Serial { get; set; }

    public int? Sttct { get; set; }

    public string MaCt { get; set; }

    public string MaKho { get; set; }

    public string MaGn { get; set; }

    public string LyDo { get; set; }

    public string Ponumber { get; set; }

    public string GhiChu { get; set; }

    public string DienGiai { get; set; }

    public DateTime? Ngay { get; set; }

    public int? Xacnhan { get; set; }

    public string NguoiDn { get; set; }

    public string MaDn { get; set; }

    public string NhaMay { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public string NghiemThu { get; set; }

    public int? Flag { get; set; }

    public virtual ICollection<NvlNhapXuatItem> NvlNhapXuatItems { get; set; } = new List<NvlNhapXuatItem>();
}