// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNghiemThuItem
{
    public int Serial { get; set; }

    public int? SerialNt { get; set; }

    public int? SerialBbitem { get; set; }

    public string CapDoKt { get; set; }

    public DateTime? NgayGioBatDau { get; set; }

    public DateTime? NgayGioKetThuc { get; set; }

    public double? Slmau { get; set; }

    public double? SlthucTe { get; set; }

    public double? Slloi { get; set; }

    public string DienGiai { get; set; }

    public string KetLuan { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }
}