// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNghiemThuTieuChuan
{
    public int Serial { get; set; }

    public string Slin { get; set; }

    public int? Slmin { get; set; }

    public int? Slmax { get; set; }

    public int? Slmau { get; set; }

    public int? SlchapNhan { get; set; }

    public string TieuChuan { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }
}