// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNhomHang
{
    public int Serial { get; set; }

    public string MaNhom { get; set; }

    public string TenNhom { get; set; }

    public string PhanLoai { get; set; }

    public string HuongDan { get; set; }

    public string KeySearch { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public virtual ICollection<NvlHangHoa> NvlHangHoas { get; set; } = new List<NvlHangHoa>();
}