// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNhapXuatLyDo
{
    public int Serial { get; set; }

    public string MaLyDo { get; set; }

    public string LyDo { get; set; }

    public string Tag { get; set; }
}