// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNghiemThuBienBan
{
    public int Serial { get; set; }

    public string TenBb { get; set; }

    public string BieuMau { get; set; }

    public DateTime? NgayBanHanh { get; set; }

    public int? Version { get; set; }

    public int? Active { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public string MauBbin { get; set; }

    public virtual ICollection<NvlNghiemThuBienBanItem> NvlNghiemThuBienBanItems { get; set; } = new List<NvlNghiemThuBienBanItem>();

    public virtual ICollection<NvlNghiemThuDienGiai> NvlNghiemThuDienGiais { get; set; } = new List<NvlNghiemThuDienGiai>();
}