// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNghiemThuMaster
{
    public int Serial { get; set; }

    public int? SerialLink { get; set; }

    public string TableName { get; set; }

    public int? SerialBb { get; set; }

    public int? SerialNhapXuat { get; set; }

    public string LoaiVatTu { get; set; }

    public string MaHang { get; set; }

    public string MaNcc { get; set; }

    public string DiaDiemNhap { get; set; }

    public DateTime? NgayKiemTra { get; set; }

    public DateTime? NgayHangVe { get; set; }

    public DateTime? NgayNhapKho { get; set; }

    public string Dvt { get; set; }

    public double? SoLuong { get; set; }

    public string DauTuan { get; set; }

    public string HieuLucGiayCn { get; set; }

    public string HieuLucTest { get; set; }

    public string LoSanXuat { get; set; }

    public string LoPhuKien { get; set; }

    public string MaSp { get; set; }

    public string Tem { get; set; }

    public string ToKhai { get; set; }

    public string NhaMay { get; set; }

    public string GhiChu { get; set; }

    public string KetLuanBb { get; set; }

    public int? IdgroupBb { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public int? CheckPrint { get; set; }
}