// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNhaCungCap
{
    public int Serial { get; set; }

    public string NhomNcc { get; set; }

    public string MaNcc { get; set; }

    public string TenNcc { get; set; }

    public string MaSoThue { get; set; }

    public string DiaChi { get; set; }

    public string TinhThanh { get; set; }

    public string QuocGia { get; set; }

    public string DienThoaiBan { get; set; }

    public string DiDong { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public string MaNganHang { get; set; }

    public string SoTk { get; set; }

    public string TenTk { get; set; }

    public string DaiDienPl { get; set; }

    public string MaChungChi { get; set; }

    public string TinhTrangThue { get; set; }

    public DateTime? NgaySoatXet { get; set; }

    public string NguoiSoatXet { get; set; }

    public string SwiftCode { get; set; }

    public string LoaiHinhKinhDoanh { get; set; }

    public string NhomMatHang { get; set; }

    public string TinhTrang { get; set; }

    public string GhiChu { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }

    public virtual ICollection<NvlDonDatHangItem> NvlDonDatHangItems { get; set; } = new List<NvlDonDatHangItem>();
}