// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlNhapXuatItem
{
    public int Serial { get; set; }

    public int SerialCt { get; set; }

    public int? SerialLink { get; set; }

    public int? SerialKhdh { get; set; }

    public string TableName { get; set; }

    public string MaHang { get; set; }

    public string Dvt { get; set; }

    public decimal Slnhap { get; set; }

    public decimal Slxuat { get; set; }

    public decimal DonGia { get; set; }

    public decimal SlnhapTt { get; set; }

    public decimal SlxuatTt { get; set; }

    public string Dvttt { get; set; }

    public double TyLeQuyDoi { get; set; }

    public string KhachHangXuatXu { get; set; }

    public DateTime? NgayHetHan { get; set; }

    public string MaKien { get; set; }

    public string SoLo { get; set; }

    public string SoXe { get; set; }

    public string GhiChu { get; set; }

    public string Barcode { get; set; }

    public string MaSp { get; set; }

    public string ArticleNumber { get; set; }

    public string UserInsert { get; set; }

    public string ViTri { get; set; }

    public string DauTuan { get; set; }

    public DateTime? NgaySanXuat { get; set; }

    public DateTime? NgayInsert { get; set; }

    public int? Flag { get; set; }

    public virtual NvlHangHoa MaHangNavigation { get; set; }

    public virtual NvlNhapXuat SerialCtNavigation { get; set; }
}