// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlReportDetail
{
    public int Serial { get; set; }

    public int? SerialLink { get; set; }

    public int? Stt { get; set; }

    public string TableName { get; set; }

    public string NameRp { get; set; }

    public string ShowNameRp { get; set; }

    public string TextRp { get; set; }

    public string NameReport { get; set; }

    public string UserInsert { get; set; }

    public string TypeRecent { get; set; }
}