// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlSoDoKho
{
    public int Serial { get; set; }

    public string Hang { get; set; }

    public string ViTri { get; set; }

    public string NhaMay { get; set; }

    public string MaKho { get; set; }

    public string Ke { get; set; }

    public string Day { get; set; }

    public string Pallet { get; set; }

    public string Tang { get; set; }
}