// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlThanhToan
{
    public int Serial { get; set; }

    public string NoiTt { get; set; }

    public string MaKn { get; set; }

    public string MaCttt { get; set; }

    public string LyDo { get; set; }

    public DateTime? Ngay { get; set; }

    public string DienGiai { get; set; }

    public string UserIns { get; set; }

    public string UserUp { get; set; }

    public int? Type { get; set; }

    public int? Flag { get; set; }

    public int? SignType { get; set; }

    public DateTime? NgayInsert { get; set; }

    public string NguoiXacNhan { get; set; }

    public DateTime? NgayXacNhan { get; set; }
}