// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlThanhToanItem
{
    public int Serial { get; set; }

    public int? MaTt { get; set; }

    public int? MaCt { get; set; }

    public decimal? SoTien { get; set; }

    public string UserInsert { get; set; }

    public DateTime? NgayInsert { get; set; }
}