// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NFCWebBlazor.Models;

public partial class NvlViTri
{
    public int Serial { get; set; }

    public int? SerialNk { get; set; }

    public string MaHang { get; set; }

    public string ViTri { get; set; }

    public string GroupPallet { get; set; }

    public string UserInsert { get; set; }

    public string MaKho { get; set; }

    public string NhaMay { get; set; }

    public DateTime? NgayInsert { get; set; }
}